name: Update NFL Scores

on:
  schedule:
    # Runs every Tuesday at 6 AM UTC (midnight CT, 1 AM ET)
    - cron: '0 6 * * 2'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  actions: read

jobs:
  update-scores:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install node-fetch
    
    - name: Clean up tracking of unwanted files
      run: |
        # Remove any npm files from git tracking if they exist
        git rm --cached package.json package-lock.json node_modules -r 2>/dev/null || true
        # Ensure .gitignore is respected
        git reset HEAD .
    
    - name: Update NFL scores
      run: node .github/scripts/update-scores.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        # Check if nfl-schedule.js has been modified
        if git diff --exit-code nfl-schedule.js > /dev/null 2>&1; then
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes detected in nfl-schedule.js"
        else
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Changes detected in nfl-schedule.js"
        fi
    
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        # Stage only the NFL schedule file
        git add nfl-schedule.js
        # Check if there's actually something to commit
        if git diff --cached --exit-code > /dev/null 2>&1; then
          echo "No staged changes to commit"
          exit 0
        fi
        git commit -m "Auto-update NFL scores - $(date)"
        # Pull the latest changes to avoid non-fast-forward error
        git fetch origin main
        git rebase origin/main
        git push origin main